// frontend/src/components/PictogramGrid.vue
<template>
  <div class="p-4 h-full overflow-auto custom-scrollbar md:overflow-scroll">
    <!-- Alerta de error -->
    <div v-if="errorMessage" class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
      <strong class="font-bold">Error: </strong>
      <span class="block sm:inline">{{ errorMessage }}</span>
      <button @click="testConnection" class="ml-2 bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded text-xs">
        Probar conexión
      </button>
    </div>
    
    <!-- Información de diagnóstico -->
    <div v-if="connectionStatus" class="mb-4 bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded">
      <strong class="font-bold">Estado: </strong>
      <span class="block sm:inline">{{ connectionStatus }}</span>
    </div>
    
    <!-- Indicador de carga para pictogramas -->
    <div v-if="loadingPictograms" class="flex items-center justify-center p-8">
      <div class="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-green-500 mr-2"></div>
      <span>Cargando pictogramas...</span>
    </div>
    
    <!-- Resto del contenido -->
    <div v-else-if="pictograms.length === 0" class="flex flex-col items-center space-y-6">
      <div class="text-center text-gray-500 mt-8 mb-4">
        No se encontraron pictogramas en esta carpeta (ID: {{ folderId }})
      </div>
      
      <div 
        class="flex flex-col items-center justify-center bg-gray-200 border border-dashed border-gray-400 rounded-lg p-6 cursor-pointer hover:bg-gray-300 w-64 h-64"
        @click="openModal"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path d="M12 4v16m8-8H4" />
        </svg>
        <span class="text-gray-700 mt-4 font-medium">Agregar primer pictograma</span>
        <span class="text-gray-500 text-sm mt-2 text-center">Haz clic para subir un pictograma a esta carpeta</span>
      </div>
    </div>
    <div v-else class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-4">
      <PictogramCard 
        v-for="pictogram in pictograms" 
        :key="pictogram.COD_PICTOGRAMA || pictogram.id" 
        :pictogram="pictogram" 
        @click="handlePictogramClick(pictogram)"
        @pictogram-updated="handlePictogramUpdated"
        @pictogram-deleted="handlePictogramDeleted"
      />
      <div 
        class="flex flex-col items-center justify-center bg-gray-200 border border-dashed border-gray-400 rounded-lg p-4 cursor-pointer hover:bg-gray-300"
        @click="openModal"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path d="M12 4v16m8-8H4" />
        </svg>
        <span class="text-gray-500 mt-2">Subir Pictograma</span>
      </div>
    </div>
  </div>

  <!-- Modal de carga para subir pictograma -->
  <div v-if="isLoading" class="modal-overlay flex items-center justify-center">
    <div class="bg-white p-5 rounded-lg shadow-lg text-center">
      <div class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-green-500 mx-auto mb-4"></div>
      <p>Subiendo pictograma...</p>
    </div>
  </div>

  <div v-if="isModalOpen" class="modal-overlay">
    <div class="modal-content">
      <h2 class="text-lg font-bold mb-4">Subir Nuevo Pictograma</h2>
      <p class="text-sm text-gray-600 mb-4">Carpeta ID: {{ folderId }}</p>
      
      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 mb-1">Imagen:</label>
        <input 
          type="file" 
          accept="image/*" 
          @change="handleFileUpload" 
          class="input-field"
        />
        <div v-if="previewImage" class="mt-2 flex justify-center">
          <img :src="previewImage" alt="Vista previa" class="h-32 object-contain border border-gray-300 rounded p-1" />
        </div>
      </div>
      
      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 mb-1">Etiqueta:</label>
        <input 
          v-model="newPictogramLabel" 
          type="text" 
          placeholder="Ingrese el texto asociado a la imagen" 
          class="input-field"
        />
      </div>
      
      <div class="modal-actions">
        <button 
          @click="uploadPictogram" 
          class="btn-primary"
          :disabled="!selectedFile || !newPictogramLabel.trim()"
          :class="{'opacity-50 cursor-not-allowed': !selectedFile || !newPictogramLabel.trim()}"
        >
          Subir
        </button>
        <button @click="closeModal" class="btn-secondary">Cancelar</button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, watch } from "vue";
import PictogramCard from "./PictogramCard.vue";
import { fetchPictogramsByFolder, createPictogram, checkConnection } from "../api";

// Define emitted events
const emit = defineEmits(["play-pictogram", "add-to-queue"]);

const props = defineProps({
  folderId: {
    type: Number,
    required: true,
  },
});

// Variables de estado separadas para diferentes tipos de carga
const pictograms = ref([]);
const isModalOpen = ref(false);
const newPictogramLabel = ref("");
const selectedFile = ref(null);
const previewImage = ref(null);
const errorMessage = ref("");
const connectionStatus = ref("");
// Estado de carga para subir pictogramas (esto controla el modal de carga)
const isLoading = ref(false);
// Estado de carga para obtener pictogramas de una carpeta (esto controla el spinner en la vista)
const loadingPictograms = ref(false);

// Función para probar la conexión con el backend
const testConnection = async () => {
  try {
    const result = await checkConnection();
    if (result.connected) {
      connectionStatus.value = `Conectado (Status: ${result.status})`;
    } else {
      connectionStatus.value = `Error de conexión: ${result.error || result.statusText}`;
    }
    
    // Limpiar el mensaje después de 5 segundos
    setTimeout(() => {
      connectionStatus.value = "";
    }, 5000);
  } catch (error) {
    connectionStatus.value = `Error: ${error.message}`;
  }
};

const loadPictograms = async () => {
  try {
    loadingPictograms.value = true;
    errorMessage.value = "";
    console.log("Cargando pictogramas para carpeta ID:", props.folderId);
    const response = await fetchPictogramsByFolder(props.folderId);
    
    // Nos aseguramos de siempre tener un array, incluso si la respuesta es nula o indefinida
    if (!response || response.message === "No se encontraron pictogramas") {
      console.log("No hay pictogramas en esta carpeta");
      pictograms.value = [];
    } else {
      console.log("Pictogramas cargados:", response);
      pictograms.value = Array.isArray(response) ? response : [];
    }
  } catch (error) {
    console.error("Error al cargar pictogramas:", error);
    // Si el error es un 404 con "No se encontraron pictogramas", no es realmente un error
    if (error.message && (
        error.message.includes("No se encontraron pictogramas") || 
        error.message.includes("Status: 404")
      )) {
      console.log("No hay pictogramas en esta carpeta");
      pictograms.value = [];
      // No mostrar error en este caso
      errorMessage.value = "";
    } else {
      errorMessage.value = `No se pudieron cargar los pictogramas: ${error.message}`;
      pictograms.value = [];
    }
  } finally {
    loadingPictograms.value = false;
  }
};

const openModal = () => {
  isModalOpen.value = true;
};

const closeModal = () => {
  isModalOpen.value = false;
  newPictogramLabel.value = "";
  selectedFile.value = null;
  previewImage.value = null;
};

const handleFileUpload = (event) => {
  selectedFile.value = event.target.files[0];
  
  // Mostrar vista previa
  if (selectedFile.value) {
    const reader = new FileReader();
    reader.onload = (e) => {
      previewImage.value = e.target.result;
    };
    reader.readAsDataURL(selectedFile.value);
  }
};

// Mejorar significativamente la compresión de imágenes
const compressImageToBase64 = (file) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (event) => {
      const img = new Image();
      img.src = event.target.result;
      img.onload = () => {
        const canvas = document.createElement("canvas");
        // Reducir drásticamente el tamaño máximo para garantizar compatibilidad
        const maxSize = 120; // Ligeramente mayor para mantener calidad mínima aceptable
        let width = img.width;
        let height = img.height;

        if (width > height) {
          if (width > maxSize) {
            height = Math.round(height * maxSize / width);
            width = maxSize;
          }
        } else {
          if (height > maxSize) {
            width = Math.round(width * maxSize / height);
            height = maxSize;
          }
        }

        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext("2d");
        ctx.drawImage(img, 0, 0, width, height);
        
        // Usar una compresión del 80% (0.2 = 80% de compresión)
        const compressedImage = canvas.toDataURL("image/jpeg", 0.2);
        console.log(`Imagen comprimida de ${width}x${height} píxeles, tamaño: ${compressedImage.length} caracteres`);
        resolve(compressedImage);
      };
      img.onerror = (error) => reject(error);
    };
    reader.onerror = (error) => reject(error);
    reader.readAsDataURL(file);
  });
};

const uploadPictogram = async () => {
  if (!selectedFile.value || !newPictogramLabel.value.trim()) {
    alert("Por favor, selecciona una imagen y proporciona una etiqueta.");
    return;
  }

  try {
    errorMessage.value = "";
    isLoading.value = true;
    console.log("Subiendo pictograma a carpeta ID:", props.folderId);
    const compressedImage = await compressImageToBase64(selectedFile.value);
    
    // Verificar tamaño de la imagen comprimida
    console.log(`Tamaño de la imagen comprimida: ${compressedImage.length} caracteres`);
    
    if (compressedImage.length > 500000) { // Reducido a 500KB
      errorMessage.value = "La imagen es demasiado grande. Intenta con una imagen más pequeña.";
      alert("La imagen es demasiado grande incluso después de comprimirla. Por favor, selecciona una imagen más pequeña o con menos detalle.");
      isLoading.value = false;
      return;
    }
    
    const result = await createPictogram(props.folderId, newPictogramLabel.value, compressedImage);
    console.log("Resultado de la subida:", result);
    
    if (result.message && result.message.includes("Error")) {
      errorMessage.value = result.message;
      alert(`Error: ${result.message}`);
    } else if (result.error) {
      errorMessage.value = `Error: ${result.error}`;
      alert(`Error del servidor: ${result.error}`);
    } else {
      await loadPictograms();
      closeModal();
      // Mostrar mensaje de éxito
      connectionStatus.value = "Pictograma creado correctamente";
      setTimeout(() => {
        connectionStatus.value = "";
      }, 3000);
    }
  } catch (error) {
    console.error("Error al subir el pictograma:", error);
    errorMessage.value = `Error al subir el pictograma: ${error.message}`;
    alert("Ocurrió un error al subir el pictograma. Por favor, intenta de nuevo.");
  } finally {
    isLoading.value = false;
  }
};

// Manejadores para las actualizaciones y eliminaciones de pictogramas
const handlePictogramUpdated = (updatedPictogram) => {
  // Encontrar y actualizar el pictograma en la lista
  const index = pictograms.value.findIndex(p => p.COD_PICTOGRAMA === updatedPictogram.COD_PICTOGRAMA);
  if (index !== -1) {
    pictograms.value[index] = { ...pictograms.value[index], ...updatedPictogram };
    
    // Mostrar mensaje de confirmación
    connectionStatus.value = "Pictograma actualizado correctamente";
    setTimeout(() => {
      connectionStatus.value = "";
    }, 3000);
  }
};

const handlePictogramDeleted = (deletedPictogramId) => {
  // Eliminar el pictograma de la lista
  const index = pictograms.value.findIndex(p => p.COD_PICTOGRAMA == deletedPictogramId);
  if (index !== -1) {
    pictograms.value.splice(index, 1);
    
    // Mostrar mensaje de confirmación
    connectionStatus.value = "Pictograma eliminado correctamente";
    setTimeout(() => {
      connectionStatus.value = "";
    }, 3000);
  }
};

const handlePictogramClick = (pictogram) => {
  emit("play-pictogram", pictogram);
  emit("add-to-queue", pictogram);
};

onMounted(() => {
  console.log("Componente PictogramGrid montado, carpeta ID:", props.folderId);
  loadPictograms();
});

watch(() => props.folderId, (newId, oldId) => {
  console.log(`Carpeta ID cambió de ${oldId} a ${newId}`);
  loadPictograms();
});
</script>

<style scoped>
/* Scroll personalizado */
.custom-scrollbar {
  scrollbar-width: thin;
  scrollbar-color: rgba(163, 230, 53, 0.5) #f0f0f0; /* lime-400 con transparencia */
}

.custom-scrollbar::-webkit-scrollbar {
  width: 8px;
}

.custom-scrollbar::-webkit-scrollbar-thumb {
  background-color: rgb(163, 230, 53); /* lime-400 exacto */
  border-radius: 4px;
}

.custom-scrollbar::-webkit-scrollbar-track {
  background-color: #f0f0f0;
}

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background: white;
  padding: 20px;
  border-radius: 8px;
  width: 300px;
  text-align: center;
}

.input-field {
  width: 100%;
  padding: 8px;
  margin: 10px 0;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.modal-actions {
  display: flex;
  justify-content: space-between;
}

.btn-primary {
  background-color: rgb(163, 230, 53); /* lime-400 exacto */
  color: white;
  padding: 8px 16px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.btn-primary:hover {
  background-color: rgb(132, 204, 22); /* lime-500 para hover */
}

.btn-secondary {
  background-color: #f44336;
  color: white;
  padding: 8px 16px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
</style>

// frontend/src/components/PictogramGrid.jsx
"use client"

import { useState, useEffect } from "react"
import PictogramCard from "./PictogramCard"
import { fetchPictogramsByFolder, createPictogram } from "../api"
import PictogramSearch from "./PictogramSearch";

// Removed testConnection and connectionStatus related code
function PictogramGrid({ folderId, onPlayPictogram, onAddToQueue }) {
  // Separate state variables for different types of loading
  const [pictograms, setPictograms] = useState([])
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [newPictogramLabel, setNewPictogramLabel] = useState("")
  const [selectedFile, setSelectedFile] = useState(null)
  const [previewImage, setPreviewImage] = useState(null)
  const [errorMessage, setErrorMessage] = useState("")
  const [successMessage, setSuccessMessage] = useState("")
  // Loading state for uploading pictograms (controls the loading modal)
  const [isLoading, setIsLoading] = useState(false)
  // Loading state for fetching pictograms from a folder (controls the spinner in the view)
  const [loadingPictograms, setLoadingPictograms] = useState(false)
  const [filteredPictograms, setFilteredPictograms] = useState([])

  const loadPictograms = async () => {
    try {
      setLoadingPictograms(true)
      setErrorMessage("")
      console.log("Cargando pictogramas para la carpeta ID:", folderId)
      const response = await fetchPictogramsByFolder(folderId)

      // Make sure we always have an array, even if the response is null or undefined
      if (!response || response.message === "No se encontraron pictogramas") {
        console.log("No hay pictogramas en esta carpeta")
        setPictograms([])
        setFilteredPictograms([])
      } else {
        console.log("Pictogramas cargados:", response)
        const pictogramsArray = Array.isArray(response) ? response : []
        setPictograms(pictogramsArray)
        setFilteredPictograms(pictogramsArray)
      }
    } catch (error) {
      console.error("Error al cargar pictogramas:", error)
      // If the error is a 404 with "No pictograms found", it's not really an error
      if (
        error.message &&
        (error.message.includes("No se encontraron pictogramas") || error.message.includes("Status: 404"))
      ) {
        console.log("No hay pictogramas en esta carpeta")
        setPictograms([])
        setFilteredPictograms([])
        // Don't show error in this case
        setErrorMessage("")
      } else {
        setErrorMessage(`No se pudieron cargar los pictogramas: ${error.message}`)
        setPictograms([])
        setFilteredPictograms([])
      }
    } finally {
      setLoadingPictograms(false)
    }
  }

  const openModal = () => {
    setIsModalOpen(true)
  }

  const closeModal = () => {
    setIsModalOpen(false)
    setNewPictogramLabel("")
    setSelectedFile(null)
    setPreviewImage(null)
  }

  const handleFileUpload = (event) => {
    const file = event.target.files[0]
    setSelectedFile(file)

    // Show preview
    if (file) {
      const reader = new FileReader()
      reader.onload = (e) => {
        setPreviewImage(e.target.result)
      }
      reader.readAsDataURL(file)
    }
  }

  // Mejora la compresión de imágenes (reducción significativa de tamaño)
  const compressImageToBase64 = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = (event) => {
        const img = new Image()
        img.src = event.target.result
        img.onload = () => {
          const canvas = document.createElement("canvas")
          // Reducir el tamaño máximo a 100px para mayor compresión
          const maxSize = 100
          let width = img.width
          let height = img.height

          if (width > height) {
            if (width > maxSize) {
              height = Math.round((height * maxSize) / width)
              width = maxSize
            }
          } else {
            if (height > maxSize) {
              width = Math.round((width * maxSize) / height)
              height = maxSize
            }
          }

          canvas.width = width
          canvas.height = height
          const ctx = canvas.getContext("2d")
          ctx.drawImage(img, 0, 0, width, height)

          // Usar 0.15 para una compresión más agresiva (85% de compresión)
          const compressedImage = canvas.toDataURL("image/jpeg", 0.15)
          console.log(`Imagen comprimida: ${width}x${height} pixels, tamaño: ${compressedImage.length} caracteres`)
          resolve(compressedImage)
        }
        img.onerror = (error) => reject(error)
      }
      reader.onerror = (error) => reject(error)
      reader.readAsDataURL(file)
    })
  }

const uploadPictogram = async () => {
  if (!selectedFile || !newPictogramLabel.trim()) {
    alert("Por favor selecciona una imagen y proporciona una etiqueta.");
    return;
  }

  try {
    setErrorMessage("");
    setIsLoading(true);
    console.log("Subiendo pictograma a la carpeta ID:", folderId);

    // Comprimir la imagen antes de enviarla
    const compressedImage = await compressImageToBase64(selectedFile);
    
    // Extraer solo los datos Base64 sin los metadatos
    const base64Data = compressedImage.split(',')[1];
    
    // Enviar la imagen comprimida con ambos nombres de campo para asegurar compatibilidad
    const result = await createPictogram(
      folderId, 
      newPictogramLabel, 
      base64Data
    );
    
    console.log("Resultado de subida:", result);

    if (result.message && result.message.includes("Error")) {
      setErrorMessage(result.message);
      alert(`Error: ${result.message}`);
    } else if (result.error) {
      setErrorMessage(`Error: ${result.error}`);
      alert(`Error del servidor: ${result.error}`);
    } else {
      await loadPictograms();
      closeModal();
      // Show success message
      setSuccessMessage("Pictograma creado con éxito");
      setTimeout(() => {
        setSuccessMessage("");
      }, 3000);
    }
  } catch (error) {
    console.error("Error al subir pictograma:", error);
    setErrorMessage(`Error al subir pictograma: ${error.message}`);
    alert("Ha ocurrido un error al subir el pictograma. Por favor intenta nuevamente.");
  } finally {
    setIsLoading(false);
  }
};

// Manejadores para actualizaciones de pictogramas y búsqueda
  const handlePictogramUpdated = (updatedPictogram) => {
    // Actualizar el pictograma en la lista
    setPictograms((prevPictograms) => {
      const updated = prevPictograms.map((p) => {
        if (p.COD_PICTOGRAMA === updatedPictogram.COD_PICTOGRAMA) {
          return { ...p, ...updatedPictogram }
        }
        return p
      });
      setFilteredPictograms(updated);
      return updated;
    })

    // Mostrar mensaje de confirmación
    setSuccessMessage("Pictograma actualizado con éxito")
    setTimeout(() => {
      setSuccessMessage("")
    }, 3000)
  }

  const handlePictogramDeleted = (deletedPictogramId) => {
    // Eliminar el pictograma de la lista
    setPictograms((prevPictograms) => {
      const filtered = prevPictograms.filter((p) => p.COD_PICTOGRAMA != deletedPictogramId);
      setFilteredPictograms(filtered);
      return filtered;
    })

    // Mostrar mensaje de confirmación
    setSuccessMessage("Pictograma eliminado con éxito")
    setTimeout(() => {
      setSuccessMessage("")
    }, 3000)
  }

  const handlePictogramClick = (pictogram) => {
    // Solo agregamos a la cola sin reproducir sonido automáticamente
    onAddToQueue(pictogram)
    // Mostramos feedback visual de que se agregó a la cola
    setSuccessMessage(`Pictograma "${pictogram.FRASE || pictogram.label}" agregado a la cola`)
    setTimeout(() => {
      setSuccessMessage("")
    }, 1500)
  }

  const handleSearch = (results) => {
    setFilteredPictograms(results);
  };

  // Load pictograms when component mounts or folderId changes
  useEffect(() => {
    const loadPictograms = async () => {
      try {
        setLoadingPictograms(true);
        const response = await fetchPictogramsByFolder(folderId);
        setPictograms(response);
        setFilteredPictograms(response);
      } catch (error) {
        console.error("Error al cargar pictogramas:", error);
        setPictograms([]);
        setFilteredPictograms([]);
      } finally {
        setLoadingPictograms(false);
      }
    };

    if (folderId) {
      loadPictograms();
    }
  }, [folderId]);

  return (
    <div className="p-4 h-full overflow-auto custom-scrollbar md:overflow-scroll">
      {/* Error alert */}
      {errorMessage && (
        <div className="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          <strong className="font-bold">Error: </strong>
          <span className="block sm:inline">{errorMessage}</span>
        </div>
      )}

      {/* Success message */}
      {successMessage && (
        <div className="mb-4 bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded">
          <strong className="font-bold">Estado: </strong>
          <span className="block sm:inline">{successMessage}</span>
        </div>
      )}

      {/* Loading indicator for pictograms */}
      {loadingPictograms ? (
        <div className="flex items-center justify-center p-8">
          <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-green-500 mr-2"></div>
          <span>Cargando pictogramas...</span>
        </div>
      ) : pictograms.length === 0 ? (
        <div className="flex flex-col items-center space-y-6">
          <div className="text-center text-gray-500 mt-8 mb-4">No se encontraron pictogramas en esta carpeta (ID: {folderId})</div>

          <div
            className="flex flex-col items-center justify-center bg-gray-200 border border-dashed border-gray-400 rounded-lg p-6 cursor-pointer hover:bg-gray-300 w-64 h-64"
            onClick={openModal}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-16 w-16 text-gray-500"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth="2"
            >
              <path d="M12 4v16m8-8H4" />
            </svg>
            <span className="text-gray-700 mt-4 font-medium">Añadir primer pictograma</span>
            <span className="text-gray-500 text-sm mt-2 text-center">Haz clic para subir un pictograma a esta carpeta</span>
          </div>
        </div>
      ) : (
        <div>
          <PictogramSearch pictograms={pictograms} onSearch={handleSearch} />
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-4 mt-4">
            {filteredPictograms.map((pictogram) => (
              <PictogramCard
                key={pictogram.COD_PICTOGRAMA || pictogram.id}
                pictogram={pictogram}
                onClick={() => handlePictogramClick(pictogram)}
                onPictogramUpdated={handlePictogramUpdated}
                onPictogramDeleted={handlePictogramDeleted}
              />
            ))}
            <div
              className="flex flex-col items-center justify-center bg-gray-200 border border-dashed border-gray-400 rounded-lg p-4 cursor-pointer hover:bg-gray-300"
              onClick={openModal}
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-12 w-12 text-gray-500"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M12 4v16m8-8H4" />
              </svg>
              <span className="text-gray-500 mt-2">Subir Pictograma</span>
            </div>
          </div>
        </div>
      )}

      {/* Loading modal for uploading pictogram */}
      {isLoading && (
        <div className="modal-overlay flex items-center justify-center fixed inset-0 bg-black bg-opacity-50 z-50">
          <div className="bg-white p-5 rounded-lg shadow-lg text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-green-500 mx-auto mb-4"></div>
            <p>Subiendo pictograma...</p>
          </div>
        </div>
      )}

      {isModalOpen && (
        <div className="modal-overlay fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="modal-content bg-white p-6 rounded-lg shadow-lg w-80 max-w-md">
            <h2 className="text-lg font-bold mb-4">Subir Nuevo Pictograma</h2>
            <p className="text-sm text-gray-600 mb-4">ID de Carpeta: {folderId}</p>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 mb-1">Imagen:</label>
              <input
                type="file"
                accept="image/*"
                onChange={handleFileUpload}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg"
              />
              {previewImage && (
                <div className="mt-2 flex justify-center">
                  <img
                    src={previewImage || "/placeholder.svg"}
                    alt="Vista previa"
                    className="h-32 object-contain border border-gray-300 rounded p-1"
                  />
                </div>
              )}
            </div>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 mb-1">Etiqueta:</label>
              <input
                value={newPictogramLabel}
                onChange={(e) => setNewPictogramLabel(e.target.value)}
                type="text"
                placeholder="Introduce texto asociado con la imagen"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg"
              />
            </div>

            <div className="flex justify-between">
              <button
                onClick={uploadPictogram}
                className={`px-4 py-2 bg-lime-400 text-white rounded hover:bg-lime-500 ${
                  !selectedFile || !newPictogramLabel.trim() ? "opacity-50 cursor-not-allowed" : ""
                }`}
                disabled={!selectedFile || !newPictogramLabel.trim()}
              >
                Subir
              </button>
              <button onClick={closeModal} className="px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600">
                Cancelar
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  )
}

export default PictogramGrid
